#!/usr/bin/env bash

deploy() {
  lift deploy
}

build() {
  dpkg-scanpackages -m debs > Packages
  sed -i '' -E '/^(Homepage|Depiction|Sponsor|Tag)/d' Packages

  rm Packages.bz2
  rm Packages.gz
  bzip2 -k Packages
  gzip -k Packages
}

serve() {
  waiter --dev
}
